### ISSUE TITLE
At least once delivery, exception handling and graceful shutdown with the processor

### ISSUE THREAD

**Issue by cwe1ss** [Azure/azure-event-hubs-dotnet#186]
I need to process 100% of my events - IIUC this is currently not possible in a nice way:

* If processing an event fails and I do NOT catch exceptions within my `IEventProcessor.ProcessEventsAsync`-method, the PartitionPump calls `ProcessErrorAsync`. This method is supposed to be "informational" so if I just log the error here and return, the processor will just continue with the next batch -> the failed event will never be processed again.
* If I re-throw the exception in `ProcessErrorAsync` the process will crash and start over from the last checkpoint. So this method works somehow but it's also a huge overhead and very hacky. Also it's hard to implement some kind of retry-logic (e.g. exponential retries).
* If I catch exceptions within my `ProcessEventsAsync`-method I could just do the retry there and implement whatever retry-logic I want. However, I now never exit the `ProcessEventsAsync`-method in case of an error, which keeps the "[ProcessingAsyncLock](https://github.com/Azure/azure-event-hubs-dotnet/blob/dev/src/Microsoft.Azure.EventHubs.Processor/PartitionPump.cs#L93)" and prevents the host from doing a graceful shutdown with `CloseAsync`.

Did I understand this correctly and what is the recommended way to do 100% event processing?

I think I would prefer handling the retry within my `ProcessEventsAsync`-method and having a `CancellationToken` that triggers when `CloseAsync` is called.

**Comment by cwe1ss** [comment]
How about this non-breaking way to provide a `CancellationToken`:
* `PartitionPump.OpenAsync` creates a new `CancellationTokenSource` and stores it as an instance variable.
* It also passes `cancellationTokenSource.Token` to a new property in `PartitionContext`.
* `PartitionPump.CloseAsync` calls `this.cancellationTokenSource.Cancel()` as the first thing. 
* This gives users of `IEventProcessor` the possibility to check for cancellations in `ProcessEventsAsync` and `ProcessErrorsAsync`.
* If they would write a loop and NOT honor the token, they'd still be deadlocked as they are now.

**Comment by Rattenkrieg** [comment]
> If I re-throw the exception in ProcessErrorAsync the process will crash and start over from the last checkpoint.

According to current state of codebase exception will be swallowed hence no restart.
I've proposed something different but for same purposes here #172

**Comment by cwe1ss** [comment]
@Rattenkrieg If you (re-)throw an exception in `ProcessErrorAsync` it ends up [at an `Environment.FailFast` statement](https://github.com/Azure/azure-event-hubs-dotnet/blob/dev/src/Microsoft.Azure.EventHubs/Amqp/AmqpPartitionReceiver.cs#L330) which immediately terminates the process (unless I'm missing a `catch` somewhere?!). If you use an orchestrator like Service Fabric, it will then start the process again and pick up from the last checkpoint.

So I think this does what you want but as I've said in my initial comment, crashing the process is a very "brutal" way of performing at least once/exactly once delivery. My proposed CancellationToken would be a very lightweight option to give users the possibility to implement more strategies. It would however not help if you want to re-process messages since the last checkpoint.

**Comment by Rattenkrieg** [comment]
@cwe1ss 
> unless I'm missing a catch somewhere?!

You're completely right, I forgot this was fixed.

**Comment by dabunnel** [comment]
@cwe1ss Have you found an alternative to throwing from ProcessErrorAsync to achieve at-least once delivery with Event Processor Host?  If you do rethrow exceptions from that method, are there any exception types that you specifically ignore?

**Comment by cwe1ss** [comment]
@dabunnel nah, still the same situation.

@serkantkaraca Any update on this? Have you looked at the corresponding PR #187 ?

**Comment by serkantkaraca** [comment]
Sorry this tool long. We had a pile of PRs that we had to walk through in he last couple weeks. This is merged in to dev branch now.

**Comment by cwe1ss** [comment]
No worries! Thank you, this is very much appreciated!

**Comment by cwe1ss** [comment]
I'm closing this as I can now do what I want. Thanks again!

**Comment by BoeseB** [comment]
@cwe1ss Thanks for finding a solution. I have a hard time to grasp how to use it though. Do you mind sharing how to use it properly? Do I just call CloseAsync in my ProcessEventsAsync method if there is an error that should stop the processing?

**Comment by dariusjs** [comment]
I've also run into this and seem to be dropping some records. @cwe1ss  do you have a rough skeleton of enforcing the at-least-once strategy?

**Comment by richp582** [comment]
Bumping because I'm looking into this too...

**Comment by serkantkaraca** [comment]
> Bumping because I'm looking into this too...

The thread is already closed with API improvement. Can you open a new one?

**Comment by richp582** [comment]
> > Bumping because I'm looking into this too...
> 
> The thread is already closed with API improvement. Can you open a new one?

Sorry, meant looking for an example of using the API improvement mentioned above.
