### ISSUE TITLE
Cannot access a disposed object. Object name: 'AmqpDataMessage'

### ISSUE THREAD

**Issue by sflusov** [Azure/azure-event-hubs-dotnet#274]
## Actual Behavior
During the day we are receiving not many exceptions from EventHub SDK. (System.ObjectDisposedException: Cannot access a disposed object. Object name: 'AmqpDataMessage') 

It looks strange, because in our code there no places where we call Dispose for client or batch message.

Please have a look code which we use for sending messages:
```
private void ProcessEvents()
{
    while (!_isDisposed)
    {
        bool result = _autoResetEvent.WaitOne();
        while (!_isDisposed)
        {
            var batch = (Microsoft.Azure.EventHubs.EventDataBatch)null;
            lock (_queue)
            {
                while (!_isDisposed)
                {
                    var locEvent = (EventDataWrapper)null;
                    if (!_queue.TryPeek(out locEvent))
                        break;

                    if (batch == null)
                        batch = _sender.CreateBatch();

                    var binEvent = Encoding.UTF8.GetBytes(locEvent.Data);
                    var hubEvent = new Microsoft.Azure.EventHubs.EventData(binEvent);
                    if (!batch.TryAdd(hubEvent))
                        break;
                }
            }
            
            if (batch != null)
	      _sender.SendAsync(batch);
        }
    }
}
```

Below you could see stack trace received from EventHub SDK:
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'AmqpDataMessage'.
at Microsoft.Azure.Amqp.AmqpMessage.ThrowIfDisposed()
at Microsoft.Azure.Amqp.SendingAmqpLink.BeginSendMessage(AmqpMessage message, ArraySegment`1 deliveryTag, ArraySegment`1 txnId, TimeSpan timeout, AsyncCallback callback, Object state)
at Microsoft.Azure.Amqp.SendingAmqpLink.<>c__DisplayClass11_0.<SendMessageAsync>b__0(AsyncCallback c, Object s)
at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
at Microsoft.Azure.Amqp.SendingAmqpLink.SendMessageAsync(AmqpMessage message, ArraySegment`1 deliveryTag, ArraySegment`1 txnId, TimeSpan timeout)
at Microsoft.Azure.EventHubs.Amqp.AmqpEventDataSender.<OnSendAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.Azure.EventHubs.Amqp.AmqpEventDataSender.<OnSendAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.EventHubs.PartitionSender.<SendAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.EventHubs.PartitionSender.<SendAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at DC.Azure.Api.Services.PartitionEventSender.ProcessEvents() 
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at DC.Azure.Api.Controllers.v1.EventsController.<RegisterEvent>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NewRelic.Providers.Wrapper.AspNetCore.WrapPipelineMiddleware.<Invoke>d__3.MoveNext()
```

## Versions  
- OS platform and version: Microsoft Windows Server 2012 R2 Datacenter (6.3.9600 Build 9600)
- .NET Version: .NET Core 2.0
- NuGet package version or commit ID: Microsoft.Azure.EventHubs (2.0.0)

**Comment by serkantkaraca** [comment]
Thanks for reporting this. While I check the code, can you see if you are able to reproduce this somehow?

**Comment by serkantkaraca** [comment]
Do you have a retry block in PartitionEventSender.ProcessEvents() ? Are you retrying send on the same EventData?

**Comment by sflusov** [comment]
Hi @serkantkaraca , 

I will try to answer on your questions

> Do you have a retry block in PartitionEventSender.ProcessEvents() ? Are you retrying send on the same EventData?

We don't have any retry logic in our code, because it makes Event Hub SDK.

> Thanks for reporting this. While I check the code, can you see if you are able to reproduce this somehow?

I can't reproduce exception manually. But it is reproduce on production server 17 times per day where average traffic 640 messages per minute and uses 24 partitions.

**Comment by serkantkaraca** [comment]
I have prepared a fix already. This will be part of next client release. https://github.com/Azure/azure-event-hubs-dotnet/pull/275

**Comment by qqbuby** [comment]
The same exception also occurred on my production server.

What's the time to release a new version nuget package of Microsoft.Azure.EventHubs ?

**Comment by serkantkaraca** [comment]
I am planning a release this weeks. The fix is merged now.

**Comment by qqbuby** [comment]
@serkantkaraca There is still not any updates at https://www.nuget.org/packages/Microsoft.Azure.EventHubs/ ?

**Comment by serkantkaraca** [comment]
We are pushing a last minute change at processor host library. https://github.com/Azure/azure-event-hubs-dotnet/pull/281

One of our customers is in need of this change so postponed the release couple days.
